### ISSUE TITLE
Measure Scale

### ISSUE THREAD

**Issue by sebastian-heinz** [Arrowgene/Arrowgene.Bugs#3]
![](https://cdn.discordapp.com/attachments/528104838886719498/528109040186818560/unknown.png)

측정 스케일을 계산하는 수식이 있습니다.
사용자가 수식에 따라 측정 눈금을 변경하도록 요청했습니다.

예 : 2ndJewel
측정 규모 = 1350 / (120 * 4.5) = 2.5

현재 우리는 두 번째 보석에 2.1을 사용하고 있습니다.

모든 노래에 수식을 적용 하시겠습니까?

# English
There is a formula to calculate the scale of the measurement.
The user has requested to change the measurement scale according to the formula.

Example: 2ndJewel
Measurement scale = 1350 / (120 * 4.5) = 2.5

Currently we are using 2.1 for the second gem.

Apply formulas to all songs?

**Comment by gkfrnwkd** [comment]
We have adjusted the Measure Scale value for each song.
Therefore, there is no need to apply.

**Comment by sebastian-heinz** [comment]
![](https://cdn.discordapp.com/attachments/528104838886719498/528111032774688769/Capture.JPG)
![](https://cdn.discordapp.com/attachments/528104838886719498/528110874532118528/Capture.JPG)

Every song has individual value in our database.

모든 노래는 우리 데이터베이스에 개별적인 가치가 있습니다.

**Comment by sebastian-heinz** [comment]
We will continue to optimize judgement until we find a good setting.
